# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk
import PMFunction # Import file chức năng
import subprocess

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

# Navigation functions
def open_statistic():
    window.destroy()
    subprocess.Popen([sys.executable, "statistic.py"])

def open_prediction():
    window.destroy()
    subprocess.Popen([sys.executable, "prediction.py"])

def open_login():
    window.destroy()
    subprocess.Popen([sys.executable, "login.py"])

def open_management():
    # Already in management, do nothing
    pass

window = tk.Tk()
window.geometry("1280x720")
window.configure(bg="#ffffff")
window.title("Machine Learning UI")

canvas = tk.Canvas(
    window, bg = "#ffffff", width = 1280, height = 720,
    bd = 0, highlightthickness = 0, relief = "ridge"
)
canvas.place(x=0, y=0)

image_2 = tk.PhotoImage(file=load_asset("frame_2/1.png"))
canvas.create_image(640, 360, image=image_2)

# --- TIÊU ĐỀ KHU VỰC ---
canvas.create_text(897, 123, anchor="nw", text="List", fill="#ffffff", font=("Roboto", 32 * -1))

# --- CẤU HÌNH BỐ CỤC (LAYOUT) ---
LABEL_FONT = ("Roboto", 24 * -1)
TEXT_FONT = ("Roboto", 14)
BG_COLOR = "#34414f"
FG_COLOR = "#ffffff"
INPUT_WIDTH = 328
INPUT_HEIGHT = 40

# 1. NAME
canvas.create_text(232, 125, anchor="nw", text="Product Name", fill="#ffffff", font=LABEL_FONT)
textarea_name = tk.Text(bd=0, bg=BG_COLOR, fg=FG_COLOR, insertbackground="#ffffff", font=TEXT_FONT)
textarea_name.place(x=232, y=160, width=INPUT_WIDTH, height=INPUT_HEIGHT)

# 2. SIZE
canvas.create_text(232, 215, anchor="nw", text="Size", fill="#ffffff", font=LABEL_FONT)
textarea_size = tk.Text(bd=0, bg=BG_COLOR, fg=FG_COLOR, insertbackground="#ffffff", font=TEXT_FONT)
textarea_size.place(x=232, y=250, width=INPUT_WIDTH, height=INPUT_HEIGHT)

# 3. CODE
canvas.create_text(232, 305, anchor="nw", text="Product Code", fill="#ffffff", font=LABEL_FONT)
textarea_code = tk.Text(bd=0, bg=BG_COLOR, fg=FG_COLOR, insertbackground="#ffffff", font=TEXT_FONT)
textarea_code.place(x=232, y=340, width=INPUT_WIDTH, height=INPUT_HEIGHT)

# 4. QUANTITY
canvas.create_text(232, 395, anchor="nw", text="Quantity", fill="#ffffff", font=LABEL_FONT)
textarea_qty = tk.Text(bd=0, bg=BG_COLOR, fg=FG_COLOR, insertbackground="#ffffff", font=TEXT_FONT)
textarea_qty.place(x=232, y=430, width=INPUT_WIDTH, height=INPUT_HEIGHT)

# 5. PRICE
canvas.create_text(232, 485, anchor="nw", text="Price", fill="#ffffff", font=LABEL_FONT)
textarea_price = tk.Text(bd=0, bg=BG_COLOR, fg=FG_COLOR, insertbackground="#ffffff", font=TEXT_FONT)
textarea_price.place(x=232, y=520, width=INPUT_WIDTH, height=INPUT_HEIGHT)

# --- VÙNG HIỂN THỊ BẢNG ---
textarea_list_bg = tk.Text(bd=0, bg="#2b2b2b", fg="#FFFFFF", highlightthickness=0)
textarea_list_bg.place(x=650, y=160, width=570, height=420)

# --- HÀM GỌI CHỨC NĂNG ---

def call_display(): # Hiển thị
    PMFunction.hien_thi_du_lieu(window, textarea_name, textarea_size, textarea_code, textarea_qty, textarea_price)

def call_add(): # Thêm (Create)
    PMFunction.them_san_pham(window, textarea_name, textarea_size, textarea_code, textarea_qty, textarea_price)

def call_read(): # Đọc
    PMFunction.doc_du_lieu(textarea_name, textarea_size, textarea_code, textarea_qty, textarea_price)

def call_delete(): # Xóa
    PMFunction.xoa_san_pham(textarea_name, textarea_size, textarea_code, textarea_qty, textarea_price)

def call_update(): # Cập nhật (MỚI)
    PMFunction.cap_nhat_san_pham(window, textarea_name, textarea_size, textarea_code, textarea_qty, textarea_price)

# --- CÁC NÚT BẤM (BUTTONS) ---

button_8_image = tk.PhotoImage(file=load_asset("frame_2/2.png"))
button_8 = tk.Button(image=button_8_image, relief="flat", borderwidth=0, highlightthickness=0, command=open_login)
button_8.place(x=37, y=538, width=116, height=116)

button_9_image = tk.PhotoImage(file=load_asset("frame_2/3.png"))
button_9 = tk.Button(image=button_9_image, relief="flat", borderwidth=0, highlightthickness=0, command=open_prediction)
button_9.place(x=38, y=372, width=116, height=116)

# Nút Product Management -> Tải bảng
button_10_image = tk.PhotoImage(file=load_asset("frame_2/4.png"))
button_10 = tk.Button(image=button_10_image, relief="flat", borderwidth=0, highlightthickness=0, command=call_display)
button_10.place(x=37, y=210, width=116, height=116)

button_11_image = tk.PhotoImage(file=load_asset("frame_2/5.png"))
button_11 = tk.Button(image=button_11_image, relief="flat", borderwidth=0, highlightthickness=0, command=open_statistic)
button_11.place(x=37, y=44, width=116, height=116)

# Nút Update (Button 12) - ĐÃ GẮN LỆNH CẬP NHẬT
button_12_image = tk.PhotoImage(file=load_asset("frame_2/6.png"))
button_12 = tk.Button(image=button_12_image, relief="flat", borderwidth=0, highlightthickness=0, command=call_update)
button_12.place(x=1076, y=602, width=63, height=63)
canvas.create_text(1065, 679, anchor="nw", text="Update", fill="#ffffff", font=("Roboto", 14 * -1))

# Nút Delete (Button 13)
button_13_image = tk.PhotoImage(file=load_asset("frame_2/7.png"))
button_13 = tk.Button(image=button_13_image, relief="flat", borderwidth=0, highlightthickness=0, command=call_delete)
button_13.place(x=948, y=602, width=63, height=63)
canvas.create_text(953, 679, anchor="nw", text="Delete", fill="#ffffff", font=("Roboto", 14 * -1))

# Nút Read (Button 14)
button_14_image = tk.PhotoImage(file=load_asset("frame_2/8.png"))
button_14 = tk.Button(image=button_14_image, relief="flat", borderwidth=0, highlightthickness=0, command=call_read)
button_14.place(x=819, y=602, width=63, height=63)
canvas.create_text(819, 676, anchor="nw", text="Read", fill="#ffffff", font=("Roboto", 14 * -1))

# Nút Create (Button 15)
button_15_image = tk.PhotoImage(file=load_asset("frame_2/9.png"))
button_15 = tk.Button(image=button_15_image, relief="flat", borderwidth=0, highlightthickness=0, command=call_add)
button_15.place(x=683, y=602, width=63, height=63)
canvas.create_text(680, 677, anchor="nw", text="Create", fill="#ffffff", font=("Roboto", 14 * -1))

# Sidebar Text
canvas.create_text(41, 666, anchor="nw", text="Log Out", fill="#ffffff", font=("Roboto", 14 * -1))
canvas.create_text(42, 499, anchor="nw", text="ML Prediction", fill="#ffffff", font=("Roboto", 14 * -1))
canvas.create_text(40, 338, anchor="nw", text="Product Management", fill="#ffffff", font=("Roboto", 14 * -1))
canvas.create_text(40, 171, anchor="nw", text="Dashboard", fill="#ffffff", font=("Roboto", 14 * -1))

window.resizable(False, False)
window.mainloop()
